---
apiVersion: v1
kind: Secret
metadata:
  name: codeserver-secret
  namespace: codeserverns
  labels:
    app: codeserver
    name: codeserver-secret
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=
