---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-pvc
  namespace: codeserverns
spec:
  accessModes:
  - ReadWriteOnce
  # - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage-retain