---
apiVersion: v1
kind: Namespace
metadata:
  name: codeserverns
  labels:
    app: codeserver
    name: codeserverns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codeserver-config
  namespace: codeserverns
  labels:
    app: codeserver
    name: codeserver-config
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: codeserver.139.59.193.189.nip.io


