---
apiVersion: v1
kind: Namespace
metadata:
  name: bggns
  # good practice to label the ns
  labels:
    app: bgg
    name: bggns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-config
  namespace: bggns
  labels:
    app: bgg
    name: bgg-config
data:
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local



