---
apiVersion: v1 
kind: Service 
metadata:
  name: minio-hsvc 
  namespace: minions
spec:
  clusterIP: None
  selector:
    app: minio
  ports:
  - name: data-port
    port: 9000
    targetPort: 9000
  - name: console-port
    port: 9090
    targetPort: 9090

--- 
apiVersion: apps/v1 
kind: StatefulSet 
metadata: 
  name: minio-sts 
  namespace: minions
spec:
  replicas: 4
  serviceName: minio-hsvc
  selector: 
    matchLabels:
      app: minio
      name: minio-pod
  volumeClaimTemplates:
  - metadata: 
      name: data-vol
    spec:
      accessModes:
      - ReadWriteOnce 
      resources:
        requests:
          storage: 1Gi
      storageClassName: do-block-storage
  template:
    metadata: 
      labels:  
        app: minio
        name: minio-pod
    spec: 
      # volumes: 
      # - name: data-vol
      #   emptyDir: {}
      securityContext:
        fsGroup: 1001
      containers:
      - name: minio-container
        image: bitnami/minio:2024.8.29
        imagePullPolicy: IfNotPresent 
        # env: 
        # - name: PUID
        #   value: "1001"
        # - name: PGID
        #   value: "1000"
        envFrom:
        - configMapRef:
            name: minio-config
        - secretRef:
            name: minio-secret
        # livenessProbe:
        #   httpGet: 
        #     path: /minio/health/live
        #     port: 9000
        #   initialDelaySeconds: 60
        #   periodSeconds: 30
        ports:
        - name: data-port
          containerPort: 9000
        - name: console-port
          containerPort: 9090
        # volumeMounts:
        # - name: data-vol 
        #   mountPath: /var/lib/mysql
        volumeMounts:
        - name: data-vol
          mountPath: /data
        # resources:
        #   requests:
        #     cpu: 200m
        #     memory: 250Mi
        #   limits:
        #     cpu: 200m
        #     memory: 250Mi

---
apiVersion: v1 
kind: Service 
metadata: 
  name: minio-svc 
  namespace: minions
spec:
  type: ClusterIP 
  selector:
    app: minio
  ports:
  - name: data
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ing
  namespace: minions
  labels:
    app: minio
    name: minio-ing
spec:
  ingressClassName: nginx
  rules:
  - host: data.139.59.193.189.nip.io
    http:
      paths: 
      - path: /
        pathType: Prefix 
        backend: 
          service:
            name: minio-hsvc
            port: 
              number: 9000 #service port ont target port 
  - host: console.139.59.193.189.nip.io
    http:
      paths: 
      - path: /
        pathType: Prefix 
        backend: 
          service:
            name: minio-hsvc
            port: 
              number: 9090 #service port ont target port 